version: "3.8"

services:
  app:
    build: .
    container_name: web-app
    ports:
      - "8054:8080"
    volumes:
      - .:/app
    depends_on:
      mysql:
        condition: service_healthy
    env_file:
      - .env

  mysql:
    image: mysql:8.0.31
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: godb
      MYSQL_USER: gouser
      MYSQL_PASSWORD: gopassword
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost --silent"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:
